[build]
  base = "/"
  publish = "dist/user-management-system"
  command = "cd Frontend && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[context.production]
  command = "cd Frontend && npm run build:prod"
  environment = {
    NODE_ENV = "production"
  }
