[build]
  base = "Frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "ng serve"
  port = 4200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mysql2"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
