[build]
  base = "/"
  publish = "dist"
  command = "./build.sh Frontend"

[build.environment]
  NODE_VERSION = "18"
  PATH = "/opt/buildhome/.nvm/versions/node/v18.x.x/bin:$PATH"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
