[build]
  base = "Frontend"
  publish = "dist/Frontend"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "ng serve"
  port = 4200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/(*)"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
